bank_project/bank_app/urls.py
# file: bank_project/bank_app/urls.py

# from django.contrib import admin
from django.urls import path
from . import views, api

app_name = "bank_app"

urlpatterns = [
    path('', views.index, name='index'),
    path('account_details/<int:pk>/', views.account_details, name='account_details'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('create_account/', views.create_account, name='create_account'),
    path('transfer/', views.transfer, name='transfer'),
    path('external_transfer/', views.external_transfer, name='external_transfer'),
    path('loan/', views.loan, name='loan'),
    path('transaction_details/<int:transaction>/', views.transaction_details, name='transaction_details'),

    path('api/startExtTransfer/', api.startExtTransfer),
    path('api/recieveExtTransfer/', api.recieveExtTransfer),
    path('api/rollbackTransaction/', api.rollbackTransaction),

    path('loan-requests/', views.loan_requests_view, name='loan_requests'),
    path('loan-requests/approve/<int:loan_request_id>/', views.approve_loan_request, name='approve_loan'),
    path('loan-requests/decline/<int:loan_request_id>/', views.decline_loan_request, name='decline_loan'),

    path('staff_ledger', views.staff_ledger, name='staff_ledger'),
    path('staff_dashboard', views.staff_dashboard, name='staff_dashboard'),
    path('staff_search/', views.staff_search, name='staff_search'),
    path('staff_customer_details/<int:pk>/', views.staff_customer_details, name='staff_customer_details'),
    path('staff_account_list/<int:pk>/', views.staff_account_list, name='staff_account_list'),
    path('staff_account_details/<int:pk>/', views.staff_account_details, name='staff_account_details'),
    path('staff_new_customer', views.staff_new_customer, name="staff_new_customer"),
    path('staff_create_account/<int:user>/', views.staff_create_account, name='staff_create_account'),
    path('staff_toggle_account_status/<int:pk>/', views.staff_toggle_account_status, name='staff_toggle_account_status'),
]

bank_project/bank_project/urls.py
from django.contrib import admin
from django.urls import path, include
from two_factor.urls import urlpatterns as tf_urls

urlpatterns = [
    path('', include(tf_urls)),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('bank/', include('bank_app.urls')),
]

bank_project/bank_app/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from .models import Customer, Account, Bank


class ExternalTransferForm(forms.Form):
    amount = forms.DecimalField(label='Amount', max_digits=10)
    debit_account = forms.ModelChoiceField(label='Debit Account', queryset=Customer.objects.none())
    debit_text = forms.CharField(label='Debit Account Text', max_length=25)
    credit_bank = forms.ModelChoiceField(label='Credit Bank', queryset=Bank.objects.all())
    credit_account = forms.IntegerField(label='Credit Account Number')
    credit_text = forms.CharField(label='Credit Account Text', max_length=25)

    def clean(self):
        super().clean()

        # Ensure credit account exist
        credit_account = self.cleaned_data.get('credit_account')
        try:
            Account.objects.get(pk=credit_account)
        except ObjectDoesNotExist:
            self._errors['credit_account'] = self.error_class(['Credit account does not exist.'])

        return self.cleaned_data


class TransferForm(forms.Form):
    amount = forms.DecimalField(label='Amount', max_digits=10)
    debit_account = forms.ModelChoiceField(label='Debit Account', queryset=Customer.objects.none())
    debit_text = forms.CharField(label='Debit Account Text', max_length=25)
    credit_account = forms.IntegerField(label='Credit Account Number')
    credit_text = forms.CharField(label='Credit Account Text', max_length=25)

    def clean(self):
        super().clean()

        # Ensure credit account exist
        credit_account = self.cleaned_data.get('credit_account')
        try:
            Account.objects.get(pk=credit_account)
        except ObjectDoesNotExist:
            self._errors['credit_account'] = self.error_class(['Credit account does not exist.'])

        # Ensure positive amount
        if self.cleaned_data.get('amount') < 0:
            self._errors['amount'] = self.error_class(['Amount must be positive.'])

        return self.cleaned_data


class NewUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password')

    def clean(self):
        super().clean()
        # Ensure username do not already exists
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username):
            self._errors['username'] = self.error_class(['Username already exists.'])

        return self.cleaned_data


class UserForm(forms.ModelForm):
    username = forms.CharField(label='Username', disabled=True)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ('rank', 'phone')


class NewAccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ('name',)


class LoanForm(forms.Form):
    loan_description = forms.CharField(label='Loan Description', max_length=25)
    amount = forms.DecimalField(label='Loan Amount', max_digits=10, decimal_places=2)
    credit_account = forms.ModelChoiceField(label='Credit Account', queryset=Account.objects.none())

    def clean_credit_account(self):
        credit_account = self.cleaned_data['credit_account']
        try:
            Account.objects.get(pk=credit_account)
        except Account.DoesNotExist:
            raise forms.ValidationError('Credit account does not exist.')

        return credit_account

bank_project/bank_app/views.py
from decimal import Decimal
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, reverse, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.db import IntegrityError
from django.conf import settings
from .forms import TransferForm, UserForm, CustomerForm, NewUserForm, NewAccountForm, LoanForm, ExternalTransferForm
from .models import Account, Ledger, Customer, Bank, LoanRequest
from .errors import InsufficientFunds
from django_otp.decorators import otp_required
import requests


# View redirects users to appropiate dashboard based on their is_staff status in the user model
@login_required
def index(request):
    if request.user.is_staff:
        return HttpResponseRedirect(reverse('bank_app:staff_dashboard'))
    else:
        return HttpResponseRedirect(reverse('bank_app:dashboard'))


# View that assures user is not staff, then returns dashboard. View for all user accounts.
@login_required
def dashboard(request):
    assert not request.user.is_staff, 'Staff user trying to access customer page.'
    loan_requests = LoanRequest.objects.filter(user=request.user)
    accounts = request.user.customer.accounts
    context = {
        'accounts': accounts,
        'loan_requests': loan_requests,
    }

    return render(request, 'bank_app/dashboard.html', context)


# View checks if user is a customer, creates the account on POST and renders the form on a GET request
@login_required
def create_account(request):
    assert not request.user.is_staff, 'Staff user trying to access customer page.'
    if request.method == 'POST':
        new_account_form = NewAccountForm(request.POST)
        if new_account_form.is_valid():
            name = new_account_form.cleaned_data['name']
            Account.objects.create(user=request.user, name=name)
            return HttpResponseRedirect(reverse('bank_app:dashboard'))
    else:
        new_account_form = NewAccountForm()

    context = {
        'new_account_form': new_account_form,
    }

    return render(request, 'bank_app/create_account.html', context)


# View that shows details/transactions of a users account, checks if the user owns it before showing
@login_required
def account_details(request, pk):
    account = get_object_or_404(Account, pk=pk)
    movements = Ledger.objects.filter(account=account)
    assert not request.user.is_staff, 'Staff user trying to access customer page.'
    if not request.user == account.user:
        raise PermissionDenied('Access Denied - Not your account.')

    context = {
        'movements': movements,
        'account': account,
        'interest_rate': settings.INTEREST_RATE
    }

    return render(request, 'bank_app/account_details.html', context)


# View that shows the details of a specific transfer once it has been sent
@login_required
def transaction_details(request, transaction):
    movements = Ledger.objects.filter(transaction=transaction)
    assert not request.user.is_staff, 'Staff user trying to access customer page.'
    if not movements.filter(account__in=request.user.customer.accounts):
        raise PermissionDenied('Customer is not a part of the transaction.')

    context = {
        'movements': movements,
    }

    return render(request, 'bank_app/transaction_details.html', context)


# View for transfering money between accounts, asserts that only users can transfer on their own behalf
@login_required
def transfer(request):
    assert not request.user.is_staff, 'Staff user trying to access the customer page.'

    if request.method == 'POST':
        form = TransferForm(request.POST)
        form.fields['debit_account'].queryset = request.user.customer.accounts
        if form.is_valid():
            amount = form.cleaned_data['amount']
            debit_account = Account.objects.get(pk=form.cleaned_data['debit_account'].pk)
            debit_text = form.cleaned_data['debit_text']
            credit_account = Account.objects.get(pk=form.cleaned_data['credit_account'])
            credit_text = form.cleaned_data['credit_text']
            try:
                transfer = Ledger.transfer(amount, debit_account, debit_text, credit_account, credit_text)
                return transaction_details(request, transfer)
            except InsufficientFunds:
                context = {
                    'title': 'Transfer Error',
                    'error': 'Insufficient funds for transfer.'
                }
                return render(request, 'bank_app/error.html', context)
    else:
        form = TransferForm()
    form.fields['debit_account'].queryset = request.user.customer.accounts
    extform = ExternalTransferForm()
    extform.fields['debit_account'].queryset = request.user.customer.accounts
    extform.fields['credit_bank'].queryset = Bank.objects.all()
    context = {
        'form': form,
        'extform': extform,
    }
    return render(request, 'bank_app/transfer.html', context)


@login_required
def external_transfer(request):
    assert not request.user.is_staff, 'Staff user trying to access the customer page.'

    if request.method == 'POST':
        extform = ExternalTransferForm(request.POST)
        extform.fields['debit_account'].queryset = request.user.customer.accounts
        extform.fields['credit_bank'].queryset = Bank.objects.all()

        if extform.is_valid():
            amount = extform.cleaned_data['amount']
            debit_account = Account.objects.get(pk=extform.cleaned_data['debit_account'].pk)
            debit_text = extform.cleaned_data['debit_text']
            credit_bank_address = extform.cleaned_data['credit_bank'].address
            credit_account = extform.cleaned_data['credit_account']
            credit_text = extform.cleaned_data['credit_text']

            # Get debit_bank_address from the current customer's bank
            debit_bank_address = request.user.customer.bank.address

            try:

                # Check if the transfer amount exceeds the available balance
                if amount > debit_account.balance:
                    raise InsufficientFunds  # Raise the InsufficientFunds exception
                # Prepare the transfer payload
                transfer_payload = {
                    'amount': str(amount),  # Convert to string
                    'debit_account': debit_account.pk,
                    'debit_text': debit_text,
                    'debit_bank_address': debit_bank_address,  # Include debit_bank_address
                    'credit_bank_address': credit_bank_address,
                    'credit_account': credit_account,  # Include credit_account
                    'credit_text': credit_text,
                }

                # Construct the API URL
                api_url = f'{debit_bank_address}bank/api/startExtTransfer/'

                # Send the POST request to the API endpoint
                requests.post(api_url, json=transfer_payload)

                # Transfer successful
                return account_details(request, debit_account.pk)

            except requests.exceptions.HTTPError as e:
                # Transfer failed
                context = {
                    'title': 'Transfer Error',
                    'error': str(e)
                }
                return render(request, 'bank_app/error.html', context)

            except InsufficientFunds:
                context = {
                    'title': 'Transfer Error',
                    'error': 'Insufficient funds for transfer.'
                }
                return render(request, 'bank_app/error.html', context)

    else:
        extform = ExternalTransferForm()
        extform.fields['debit_account'].queryset = request.user.customer.accounts
        extform.fields['credit_bank'].queryset = Bank.objects.all()

    form = TransferForm()
    form.fields['debit_account'].queryset = request.user.customer.accounts

    context = {
        'form': form,
        'extform': extform,
    }

    return render(request, 'bank_app/transfer.html', context)


# View checks is user is approved for loan based on their rank
# If user is approved, on POST, a loan is created as an account with an extra is_loan = True variable.
# On GET request the loan page is rendered
@login_required
def loan(request):
    assert not request.user.is_staff, 'Staff user trying to access customer page.'

    if not request.user.customer.loan_approved:
        context = {
            'title': 'Create Loan Error',
            'error': 'You are not approved for a loan.'
        }

        return render(request, 'bank_app/error.html', context)

    if request.method == 'POST':
        form = LoanForm(request.POST)
        form.fields['credit_account'].queryset = request.user.customer.accounts

        request.user.customer.create_loan(
            Decimal(request.POST['amount']),
            request.POST['loan_description'],
            request.POST['credit_account']
        )

        # Redirect to the loan request details page or a confirmation page
        return HttpResponseRedirect(reverse('bank_app:dashboard'))
    else:
        form = LoanForm()

    form.fields['credit_account'].queryset = request.user.customer.accounts.filter(loan=False)
    context = {
        'form': form,
    }
    return render(request, 'bank_app/loan.html', context)


@login_required
def loan_requests_view(request):
    assert request.user.is_staff
    loan_requests = LoanRequest.objects.all()
    return render(request, 'bank_app/loan-requests.html', {'loan_requests': loan_requests})


@login_required
def approve_loan_request(request, loan_request_id):
    assert request.user.is_staff
    loan_request = LoanRequest.objects.get(pk=loan_request_id)
    loan_request.status = 'Approved'
    loan_request.save()

    # Run the Ledger function and create the loan

bank_project/bank_app/templates/bank_app/account_details.html
{% extends "base.html" %}
{% block main %}

<h2>Hello, {{ user.customer.full_name }}</h2>

<h3 class="account-name">{{ account.name }}</h3>
{% if account.is_active %}
<p class="tags status-tag-active">Active</p>
{% else %}
<p class="tags status-tag-inactive">Inactive</p>
{% endif %}

<h4>Balance: <span class="balance">${{ account.balance }}</span></h4>
{% if account.loan %}
<p>Interest: {{ interest_rate }}% ({{ account.loan_interest }})</p>
{% endif %}

<table>
    <tr>
        <th>Transaction</th>
        <th>Amount</th>
        <th>Date</th>
        <th>ID</th>
    </tr>
    {% for movement in movements %}
    <tr>
        <td>{{ movement.text }}</td>
        <td>{{ movement.amount }}</td>
        <td class="nowrap">{{ movement.timestamp | date:"M d, Y" }}</td>
        <td>{{ movement.transaction }}</td>
    </tr>
    {% empty %}
    <tr>
        <td colspan="4">There are no transactions yet.</td>
    </tr>
    {% endfor %}
</table>

{% endblock main %}

bank_project/bank_app/templates/bank_app/create_account.html
{% extends "base.html" %}     
{% block main %}

<h2>Hello, {{ user.customer.full_name }}</h2>

<h4>Here you can create new accounts</h4>

<form action="{% url 'bank_app:create_account' %}" method="post">
    {% csrf_token %}                                         
    <fieldset>
        <legend><h5>Create Account</h5></legend>
        {{ new_account_form }}                                           
        <button>Create new account</button>                         
    </fieldset>                                              
</form>                                                      
{% endblock main %}                                          

bank_project/bank_app/templates/bank_app/dashboard.html
{% extends "base.html" %}
{% block main %}

<h2>Hello, {{ user.customer.full_name }}</h2>

<p class="tags rank-tag">{{ user.customer.rank.name }}</p>
<h4>Accounts</h4>

<table>
    <tr>
        <th>Account Number</th>
        <th>Name</th>
        <th>Balance</th>
        <th>Status</th>
    </tr>

    {% for account in accounts %}
    <tr>
        {% csrf_token %}
        <td><a href="{% url 'bank_app:account_details' account.pk %}">{{ account.pk }}</a></td>
        <td>{{ account.name }}</td>
        <td><h5 style="margin: 5px 0">${{ account.balance }}</h5></td>
        <td>{% if account.is_active %} Active {% else %} Deactivated {% endif %}</td>
    </tr>
    {% endfor %}
</table>

<h5>Loan Applications</h5>

<table>
    <thead>
        <tr>
            <th>Amount</th>
            <th>Name</th>
            <th>Account</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        {% for loan_request in loan_requests %}
        <tr>
            <td>{{ loan_request.amount }}</td>
            <td>{{ loan_request.name }}</td>
            <td>{{ loan_request.account }}</td>
            <td>{{ loan_request.status }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock main %}

bank_project/bank_app/templates/bank_app/error.html
{% extends "base.html" %}
{% block main %}

<h1>ERROR :)</h1>

<p>{{ error }}</p>

<button onclick="goBack()">Go Back</button>

<script>
    function goBack() {
        window.history.back();
    }
</script>

{% endblock main %}}

bank_project/bank_app/templates/bank_app/index.html
<!-- bank_project/bank_app/templates/bank_app/index.html -->

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>bank</title>
    </head>
    <body>
        <h1>Bank App HTML</h1>
    </body>
</html>

bank_project/bank_app/templates/bank_app/loan-requests.html
{% extends "base.html" %}
{% block main %}
<h2>Loan Applications</h2>

<table>
    <thead>
        <tr>
            <th>Customer</th>
            <th>Amount</th>
            <th>Name</th>
            <th>Account</th>
            <th>Status</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        {% for loan_request in loan_requests %}
        <tr>
            <td>{{ loan_request.user|capfirst }}</td>
            <td>{{ loan_request.amount }}</td>
            <td>{{ loan_request.name }}</td>
            <td>{{ loan_request.account }}</td>
            <td>{{ loan_request.status }}</td>
            <td>
                {% if loan_request.status == 'Pending' %}
                <form style="float: left; padding-right: 10px;" action="{% url 'bank_app:approve_loan' loan_request.id %}" method="post">
                    {% csrf_token %}
                    <input type="submit" value="Approve">
                </form>
                <form style="float: left" action="{% url 'bank_app:decline_loan' loan_request.id %}" method="post">
                    {% csrf_token %}
                    <input type="submit" value="Decline">
                </form>
                {% else %}
                No action required
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock main %}

bank_project/bank_app/templates/bank_app/loan.html
{% extends "base.html" %}
{% block main %}

<h2>Loans</h2>

<form action="{% url 'bank_app:loan' %}" method="POST">
    {% csrf_token %}
    <fieldset>
        {{ form }}
            <button>Create Loan</button>
    </fieldset>
</form>

{% endblock main %}

bank_project/bank_app/templates/bank_app/staff_account_details.html
{% extends "base.html" %}
{% block main %}

<h2>{{ account.name }}</h2>
<h5 class="account-id">Account ID: {{ account.id }}</h5>

<h4>Balance: <span class="balance">${{ account.balance }}</span></h4>
<p>Account Status: {% if account.is_active %}Active{% else %}Deactivated{% endif %}</p>
{% if account.loan %}
<p>Interest: {{ interest_rate }}% ({{ account.loan_interest }})</p>
{% endif %}

<table>
    <tr>
        <th>Transaction</th>
        <th>Amount</th>
        <th>Date</th>
        <th>ID</th>

    </tr>
    {% for movement in movements %}
    <tr>
        <td>{{ movement.text }}</td>
        <td>{{ movement.amount }}</td>
        <td class="nowrap">{{ movement.timestamp | date:"M d, Y" }}</td>
        <td>{{ movement.transaction }}</td>
    </tr>
    {% endfor %}
</table>

{% endblock main %}

bank_project/bank_app/templates/bank_app/staff_account_list.html
<tbody id="account-list">
{% for account in accounts %}
    <tr>
        <td><a href="{% url 'bank_app:staff_account_details' account.pk %}">{{ account.pk }}</a></td>
        <td>{{ account.name }}</td>
        <td>{{ account.balance|floatformat:"2" }}</td>
        <td>
            {% if account.is_active %}
            Active  {% if account.balance >= 0 %}|  <a href="{% url 'bank_app:staff_toggle_account_status' account.pk %}">(Deactivate)</a> {% endif %}
            {% else %}
            Inactive  |  <a href="{% url 'bank_app:staff_toggle_account_status' account.pk %}">(Activate)</button>
            {% endif %}
        </td>
    </tr>
{% endfor %}
</tbody>

bank_project/bank_app/templates/bank_app/staff_dashboard.html
{% extends "base.html" %}
{% block main %}
    <h1>Welcome {{ user }}  to the staff dashboard</h1>

    </br>

    <fieldset>
        <div>
            <legend><label>Search for customer</label></legend>
            <input  name="search_term"
                    type="text"
                    placeholder="Customer Name"
                    class="form-control"
                    hx-post="{% url 'bank_app:staff_search' %}"
                    hx-trigger="keyup changed delay:500ms"
                    hx-target="#search-results"
                    hx-indicator=".htmx-indicator"
            >
            {% csrf_token %}
        </div>
        </br>

        <table>
            <thead>
                <th>ID</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Phone</th>
                <th>Email</th>
            </thead>
            <tbody id="search-results">
            </tbody>
        </table>

    </fieldset>

    </br>

{% endblock main %}

bank_project/bank_app/templates/bank_app/staff_ledger.html
{% extends "base.html" %}
{% block main %}

<h2>Epsilon Bank Ledger</h2>

<table>
    <tr>
        <th>Transaction</th>
        <th>Account</th>
        <th>Amount</th>
        <th>Date</th>
        <th>ID</th>
    </tr>
    {% for movements in ledger %}
    <tr>
        <td>{{ movements.text }}</td>
        <td class="nowrap">{{ movements.account.id }} | {{ movements.account.name }} {% if movements.account.is_active %} (active) {% else %} (deactivated) {% endif %}</td>
        <td>{{ movements.amount }}</td>
        <td class="nowrap">{{ movements.timestamp | date:"M d, Y" }}</td>
        <td>{{ movements.transaction }}</td>
    </tr>
    {% endfor %}
</table>

{% if ledger.has_other_pages %}
<ul class="pagination">
    {% if ledger.has_previous %}
    <li><a href="?page={{ ledger.previous_page_number }}">&laquo;</a></li>
    {% else %}
    <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in ledger.paginator.page_range %}
    {% if ledger.number == i %}
    <li class="active">{{ i }}</li>
    {% else %}
    <li><a href="?page={{ i }}">{{ i }}</a></li>
    {% endif %}
    {% endfor %}
    {% if ledger.has_next %}
    <li><a href="?page={{ ledger.next_page_number }}">&raquo;</a></li>
    {% else %}
    <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
</ul>
{% endif %}

{% endblock main %}

bank_project/bank_app/templates/bank_app/staff_new_customer.html
{% extends "base.html" %}

{% block main %}
<h2>Create a user</h2>
<form action="{% url 'bank_app:staff_new_customer' %}" method="post">
    {% csrf_token %}
    <fieldset>
        {{ new_user_form }}
        {{ customer_form }}
        <button>Create User</button>
    </fieldset>
</form>
{% endblock main %}

bank_project/bank_app/templates/bank_app/staff_search.html
{% for customer in customers %}
<tr>
    <td><a href="{% url 'bank_app:staff_customer_details' customer.pk %}">{{ customer.pk }}</a></td>
    <td>{{ customer.user.first_name }}</td>
    <td>{{ customer.user.last_name }}</td>
    <td>{{ customer.phone }}</td>
    <td>{{ customer.user.email }}</td>
</tr>
{% endfor %}

bank_project/bank_app/templates/bank_app/transfer.html
{% extends "base.html" %}
{% block main %}

<h2>Transfers</h2>

<form action="{% url 'bank_app:transfer' %}" method="POST">
    {% csrf_token %}
    <fieldset>
        {{ form }}
        <input type="submit" value="Transfer">
    </fieldset>
</form>

<h2>External transfer</h2>

<form action="{% url 'bank_app:external_transfer' %}" method="POST">
    {% csrf_token %}
    {{ extform.as_p }}
    <input type="submit" value="External Transfer">
</form>

{% endblock main %}