bank_project/bank_app/urls.py
# file: bank_project/bank_app/urls.py

# from django.contrib import admin
from django.urls import path
from . import views, api

app_name = "bank_app"

urlpatterns = [
    path('', views.index, name='index'),
    path('account_details/<int:pk>/', views.account_details, name='account_details'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('create_account/', views.create_account, name='create_account'),
    path('transfer/', views.transfer, name='transfer'),
    path('external_transfer/', views.external_transfer, name='external_transfer'),
    path('loan/', views.loan, name='loan'),
    path('transaction_details/<int:transaction>/', views.transaction_details, name='transaction_details'),

    path('api/startExtTransfer/', api.startExtTransfer),
    path('api/recieveExtTransfer/', api.recieveExtTransfer),
    path('api/rollbackTransaction/', api.rollbackTransaction),

    path('loan-requests/', views.loan_requests_view, name='loan_requests'),
    path('loan-requests/approve/<int:loan_request_id>/', views.approve_loan_request, name='approve_loan'),
    path('loan-requests/decline/<int:loan_request_id>/', views.decline_loan_request, name='decline_loan'),

    path('staff_ledger', views.staff_ledger, name='staff_ledger'),
    path('staff_dashboard', views.staff_dashboard, name='staff_dashboard'),
    path('staff_search/', views.staff_search, name='staff_search'),
    path('staff_customer_details/<int:pk>/', views.staff_customer_details, name='staff_customer_details'),
    path('staff_account_list/<int:pk>/', views.staff_account_list, name='staff_account_list'),
    path('staff_account_details/<int:pk>/', views.staff_account_details, name='staff_account_details'),
    path('staff_new_customer', views.staff_new_customer, name="staff_new_customer"),
    path('staff_create_account/<int:user>/', views.staff_create_account, name='staff_create_account'),
    path('staff_toggle_account_status/<int:pk>/', views.staff_toggle_account_status, name='staff_toggle_account_status'),
]

bank_project/bank_project/urls.py
from django.contrib import admin
from django.urls import path, include
from two_factor.urls import urlpatterns as tf_urls

urlpatterns = [
    path('', include(tf_urls)),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('bank/', include('bank_app.urls')),
]

bank_project/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        {% load static %}
        <link rel="stylesheet" type="text/css" href="https://cdn.simplecss.org/simple.min.css" />
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" media="screen" />
        <title>Epsilon Bank</title>
    </head>
    <body>

        <header>
            {% if user.is_staff %}
            <h1>Staff Portal</h1>
            {% else %}
            <h1>Customer Dashboard</h1>
            <p><strong>{{ user.customer.bank.name }}'s Bank</strong></p>
            {% endif %}

            <nav>
                <ul style="list-style: none">
                    {% if user.is_staff %}
                    <li><a href="{% url 'bank_app:index' %}">Staff Dashboard</a></li>
                    <li><a href="{% url 'bank_app:loan_requests' %}">Loan Requests</a></li>
                    <li><a href="{% url 'bank_app:staff_new_customer' %}">Create User</a></li>
                    <li><a href="{% url 'bank_app:staff_ledger' %}">Ledger</a></li>
                    {% else %}
                    <li><a href="{% url 'bank_app:index' %}">Dashboard</a></li>
                    <li><a href="{% url 'bank_app:create_account' %}">Create Account</a></li>
                    <li><a href="{% url 'bank_app:transfer' %}">Transfer</a></li>
                    <li><a href="{% url 'bank_app:loan' %}">Loan</a></li>
                    {% endif %}
                    {% if user.is_superuser %}
                    <li><a href="/admin">Admin</a></li>
                    {% endif %}
                    <li><a href="/account/two_factor/">Two Factor Settings</a></li>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'logout' %}">Sign out</a></li>
                    {% endif %}
                </ul>
            </nav>

        </header>

        <main>
            {% block main %} <!-- Start of the main block, allows us to use it in other documents -->
            {% endblock main %} <!-- End of the main block -->
        </main>

        <footer>
            <p>&copy; 2023 Epsilon Inc.</p>
        </footer>
        <script src="https://unpkg.com/htmx.org@1.9.0"></script>
            <script>
                document.body.addEventListener('htmx:configRequest', (event) => {
                event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
            })
        </script>
    </body>
</html>